  
pipeline {
      agent any
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, Welcome to Devops'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
			git url: 'https://github.com/MohitWadhwani/Maven-Project/single-module/'
		        bat label: '', script: 'mvn clean install'
                  }
            }
            stage('Deploy') {
                  steps {
                        echo "Deploying"
                  }
	    post {
               always {
                archiveArtifacts artifacts: '**/*.jar', onlyIfSuccessful: true
               }
            }    
        }            
    }
}
