  
pipeline {
      agent any
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, Welcome to Devops'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
		        bat label: '', script: 'mvn -f single-module/pom.xml clean install'
                  }
            }
            stage('Deploy') {
                  steps {
                        echo "Deploying"
                  }
	    post {
               always {
                archiveArtifacts artifacts: '**/*.jar', onlyIfSuccessful: true
               }
            }    
        }            
    }
}
